 export const projects = [
    {
      id: 1,
      title: "Smart Job AI",
      description:
        "An AI-powered job matching platform that connects job seekers with their perfect opportunities using intelligent resume analysis and personalized job recommendations.",
      image: '/smartJobAi.png',
      category: "Full-stack",
      tech: [
        "Next js",
        "TypeScript",
        "Mongoose",
        "Redux Toolkit",
        "Zod",
        "React-hook-form",
        "Tanstack Query",
        "Axios",
        "ImageKit",
        "bcryptjs",
        "Json Web Token",
        "Tailwind CSS",
        "Shadcn UI",
        "react-countup",
        "react-day-picker",
        "react-redux",
        "recharts",
        "sonner",
        "lucide-react",
        "framer-motion",
      ],
      github: "https://github.com/UmayerCoding1/next-smart-job-ai",
      live: "https://next-smart-job-ai.vercel.app",
      date: "2025",
      status: "Development",
    },
    {
      id: 2,
      title: "Carsetgo",
      description:
        "CarSetGo is a modern MERN stack platform for renting and selling cars, enhanced with AI features like auto description generation and image analysis. It supports user, seller, and admin roles with secure JWT auth, Stripe payments, Cloudinary uploads, and a smooth UI using Tailwind and Framer Motion.",
      image: "https://umayer--hossain.vercel.app/assets/carsetgo-D3GCAZXZ.png",
      category: "Full-stack",
      tech: [
        "mongoose",
        "Express",
        "React",
        "Node.js",
        "Tailwind CSS",
        "axios",
        "bcryptjs",
        "googleapis",
        "react-router-dom",
        "lucide-react",
        "sonner",
        "tanstack-query",
        "react-hook-form",
        "react-dropzone",
        "react-chartjs-2",
        "motion",
        "chart.js",
        "json webtoken",
        "helmet",
        "stripe",
        "multer",
        "cloudinary",
      ],
      client: "https://github.com/UmayerCoding1/CarSetGo/tree/main/client",
      server: "https://github.com/UmayerCoding1/CarSetGo/tree/main/server",
      live: "https://carsetgo.vercel.app",
      date: "2025",
      status: "Production",
    },
    {
      id: 3,
      title: "TravelBD",
      description:
        "A full-stack travel agency website featuring user authentication, destination management, booking system, and payment integration. Users can browse destinations, make bookings, and process payments securely. Admins can manage destinations, track bookings, and view analytics through an intuitive dashboard.",
      image: "https://umayer--hossain.vercel.app/assets/travelbd-CBjAG_vX.png",
      category: "Full-stack",
      tech: [
        "@types/mongoose-aggregate-paginate-v2",
        "bcrypt",
        "cloudinary",
        "cookie-parser",
        "cors",
        "dotenv",
        "express",
        "jsonwebtoken",
        "mongoose",
        "multer",
        "npm",
        "sslcommerz-lts",
        "aos",
        "axios",
        "chart.js",
        "date-fns",
        "dayjs",
        "firebase",
        "react",
        "react-chartjs-2",
        "react-date-range",
        "react-datepicker",
        "react-dom",
        "react-helmet",
        "react-hook-form",
        "react-hot-toast",
        "react-icons",
        "react-query",
        "react-router",
        "react-router-dom",
        "react-slick",
        "swiper",
        "tailwind-scrollbar",
      ],
      client: "https://github.com/UmayerCoding1/travelbd-client",
      server: "https://github.com/UmayerCoding1/travelbd-server",
      live: "https://travelbd-158bd.web.app",
      date: "2024",
      status: "Production",
    },
    {
      id: 4,
      title: "E Market Hub",
      description:
        "A full-stack e-commerce platform with user authentication, product management, cart functionality, and payment integration.",
      image: "https://umayer--hossain.vercel.app/assets/ecoommers-DU9PnGyf.png",
      category: "Full-stack",
      tech: [
        "MongoDB",
        "Express",
        "React",
        "Node.js",
        "Tailwind CSS",
        "axios",
        "react-router-dom",
        "react-hook-form",
        "react-icons",
        "react-hot-toast",
        "tanstack-query",
        "react-tabs",
        "swiper",
        "firebase",
        "react-pdf",
        "MUI",
        "json webtoken",
        "helmet",
        "sslcommerz",
        "multer",
        "cloudinary",
      ],
      client: "https://github.com/UmayerCoding1/eMarket-hub-client",
      server: "https://github.com/UmayerCoding1/E-Market-hub-server",
      live: "https://emarket-hub.web.app",
      date: "2024",
      status: "Production",
    },
    {
      id: 5,
      title: "Modulars",
      description:
        "A full-stack e-commerce platform with user authentication, product management, cart functionality, and payment integration.",
      image: "/fp1.png",
      category: "Frontend",
      tech: [
        "MongoDB",
        "Express",
        "React",
        "Node.js",
        "Tailwind CSS",
        "axios",
        "react-router-dom",
        "react-hook-form",
        "react-icons",
        "react-hot-toast",
        "tanstack-query",
        "react-tabs",
        "swiper",
        "firebase",
        "react-pdf",
        "MUI",
        "json webtoken",
        "helmet",
        "sslcommerz",
        "multer",
        "cloudinary",
      ],
      // client: "https://github.com/UmayerCoding1/eMarket-hub-client",
      // server: "https://github.com/UmayerCoding1/E-Market-hub-server",
      live: "https://modulars-nu.vercel.app",
      date: "2024",
      status: "Production",
    },
    {
      id: 6,
      title: "Brickwise",
      description:
        "Brickwise is a modern frontend web application designed for a real estate investment platform. It features a clean and responsive UI that allows users to explore investment opportunities through an intuitive property search by location, property type, and budget. The project focuses on strong visual hierarchy, usability, and professional design standards commonly used in fintech and real estate products. Built as a frontend-only project, it showcases my skills in responsive layouts, component-based architecture, and modern UI development using Next.js,Tailwind CSS and motion.",
      image: "/fp2.png",
      category: "Frontend",
      tech: [
        "MongoDB",
        "Express",
        "React",
        "Node.js",
        "Tailwind CSS",
        "axios",
        "react-router-dom",
        "react-hook-form",
        "react-icons",
        "react-hot-toast",
        "tanstack-query",
        "react-tabs",
        "swiper",
        "firebase",
        "react-pdf",
        "MUI",
        "json webtoken",
        "helmet",
        "sslcommerz",
        "multer",
        "cloudinary",
      ],
      // client: "https://github.com/UmayerCoding1/eMarket-hub-client",
      // server: "https://github.com/UmayerCoding1/E-Market-hub-server",
      live: "https://modulars-nu.vercel.app",
      date: "2024",
      status: "Production",
    },
    
  ];